### ISSUE TITLE
Form Events and Compatibility with upcoming release Igor

### ISSUE THREAD

**Issue by splitbrain** [zuiderkwast/dokuwiki-plugin-translate#14]
This plugin seems to make use of one or more form related action events that will be removed in the next DokuWiki release. Please have a look at https://www.patreon.com/posts/better-forms-58551930 for details.

My apologies if this has already been addressed in your code. If you have any questions on how to implement the needed changes please let me know.

**Comment by zuiderkwast** [comment]
Thanks Andreas. I'd be happy to accept a PR from anyone who's using this plugin.

I've not using this plugin or DokuWiki for years. If anyone wants to take over the maintenance (e.g. change the link in the wiki page to a fork), it's also fine.

**Comment by BallWarapol** [comment]
> Thanks Andreas. I'd be happy to accept a PR from anyone who's using this plugin.
> 
> I've not using this plugin or DokuWiki for years. If anyone wants to take over the maintenance (e.g. change the link in the wiki page to a fork), it's also fine.

It's sound sad. This is the easiest plugin for me T-T

**Comment by zuiderkwast** [comment]
@BallWarapol if you make the changes, test it with the new dokuwiki version and make a pull request, I will merge it.
